### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config从哪里下载

### ISSUE THREAD

**Issue by smallwenzi** [nacos-group/nacos-examples#1]
spring-cloud-starter-alibaba-nacos-config（版本：0.2.0.BUILD-SNAPSHOT）从哪里下载

**Comment by HaojunRen** [comment]
This project is for nacos spring, not with spring cloud. Please refer to https://github.com/spring-cloud-incubator/spring-cloud-alibaba, btw the lateset version is 0.2.0.RELEASE
这是Nacos Spring工程，跟Spring Cloud没关系，建议您访问https://github.com/spring-cloud-incubator/spring-cloud-alibaba获得Nacos Spring Cloud的最新代码和信息，顺便说一下，今天刚发布的版本是0.2.0.RELEASE

**Comment by hxy1991** [comment]
你好，0.2.0.RELEASE 已经正式发布，Maven 配置如下：

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-nacos-config</artifactId>
    <version>0.2.0.RELEASE</version>
</dependency>
```
