### ISSUE TITLE
nacos-spring-boot-config-example not working as expected

### ISSUE THREAD

**Issue by dengshenyu** [nacos-group/nacos-examples#4]
Hi,

I follow the [https://nacos.io/en-us/docs/quick-start-spring-cloud.html](https://nacos.io/en-us/docs/quick-start-spring-cloud.html) page to come here and download nacos-spring-boot-config-example. I act as what the page said, but the config does not change. Then I found that no such following line in NacosConfigApplication class:

@NacosPropertySource(dataId = "example", autoRefreshed = true)

Then I add it by myself, but it seems no NacosPropertySource annotation in spring-cloud-starter-alibaba-nacos-config-0.2.0.RELEASE. Oh....

**Comment by hxy1991** [comment]
In the current version(spring-cloud-starter-alibaba-nacos-config-0.2.0.RELEASE), it does not require configuration "@NacosPropertySource".

It is consistent with Spring Cloud Config's specification and requires "@RefreshScope" to automatically update configuration items.

Also, please make sure your Nacos Server is working find.

I hope to help you solve the problem. Thank you for your feedback.
