### ISSUE TITLE
zuul不能访问新注册的服务

### ISSUE THREAD

**Issue by gurmyCheng** [nacos-group/nacos-examples#5]
求助，springcloud中注册中心替换成nacos，用zuul代理。在zuul微服务启动之后，新注册的微服务能在nacos服务列表查看到，但通过zuul无法访问，非得zuul重启后才能访问新注册的服务。。。这是缺少什么配置吗

**Comment by HaojunRen** [comment]
这个问题，建议把这个问题提交到https://github.com/spring-cloud-incubator/spring-cloud-alibaba，根据您的文字描述，我推测是否是这个问题https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/23

**Comment by HaojunRen** [comment]
这个问题，建议把这个问题提交到
 https://github.com/spring-cloud-incubator/spring-cloud-alibaba， 根据您的文字描述，我推测是否是这个问题
 https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/23

**Comment by gurmyCheng** [comment]
> 这个问题，建议把这个问题提交到
> [https://github.com/spring-cloud-incubator/spring-cloud-alibaba，](https://github.com/spring-cloud-incubator/spring-cloud-alibaba%EF%BC%8C) 根据您的文字描述，我推测是否是这个问题
> [spring-cloud-incubator/spring-cloud-alibaba#23](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/23)

嗯  应该是一个问题，谢了，去那边更去

**Comment by gurmyCheng** [comment]
> 这个问题，建议把这个问题提交到
> [https://github.com/spring-cloud-incubator/spring-cloud-alibaba，](https://github.com/spring-cloud-incubator/spring-cloud-alibaba%EF%BC%8C) 根据您的文字描述，我推测是否是这个问题
> [spring-cloud-incubator/spring-cloud-alibaba#23](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/23)

嗯  应该是一个问题。去那边关注去。谢啦
