### ISSUE TITLE
springboot2使用nacos做配置中心，不能实时刷新

### ISSUE THREAD

**Issue by liangfutang** [nacos-group/nacos-examples#51]
springboot2使用nacos做配置中心时，服务启动的时候能接受到数据，但是页面修改后服务接受不到新的参数，不能动态刷新。使用提供的demo用例测试：nacos-spring-boot-config-example，测试。发现同样的问题

注：没有引用springcloud，仅仅是springboot服务

**Comment by yeatsinheart** [comment]
使用 @NacosValue(value = "${testvalue}", autoRefreshed = true)
